### ISSUE TITLE
How do we handle IDs that point back to originating repository

### ISSUE THREAD

**Issue by bcorrie** [airr-knowledge/issues#56]
When converting a `Repertoire` into its constituent parts in the AKC data model, how are we planning on keeping track of where the originally generated data came from. The AKC for at least data provenance and reproducibility need to track where the originating data came from.

Currently, when I am converting an ADC entity I am adding fields to the AKC LinkML generated that have `adc_` prefixed onto the ADC ID field name. For example:

```
    "Specimen": {
      "M369-S008": {
        "akc_id": "",
        "specimen_type": "Venipuncture blood samples were collected in K2EDTA-coated vacutainers",
        "tissue": {
          "label": "venous blood",
          "id": "UBERON:0013756"
        },
        "adc_repertoire_id": "5ed6859e99011334ac05e847",
        "adc_sample_processing_id": "5ed6859e99011334ac05e847",
        "adc_data_processing_id": "5ed6859e99011334ac05e847",
        "adc_study_id": "PRJNA628125",
        "adc_subject_id": "7450",
        "adc_sample_id": "M369-S008"
      }
    }
```

**Comment by schristley** [comment]
[ForeignObject](https://airr-knowledge.github.io/ak-schema/ForeignObject/) is a class I added to represent such objects. The question is how to organize. For example, do we create separate slots for each like in your example above with `adc_repertoire_id` and etc. I feel this is "messy", meaning we will have a proliferation of those slots and they are all highly customized to the repository being integrated. It would be nice to have something more generic.

I was thinking of something simple like a `source_uris` slot which holds them and use CURIE/prefixes, so to adjust your example above:

```
"Specimen": {
      "M369-S008": {
        "akc_id": "",
        "specimen_type": "Venipuncture blood samples were collected in K2EDTA-coated vacutainers",
        "tissue": {
          "label": "venous blood",
          "id": "UBERON:0013756"
        },
        "source_uris": [ "ADC_REPERTOIRE:5ed6859e99011334ac05e847", "ADC_SP:5ed6859e99011334ac05e847", "ADC_DP:5ed6859e99011334ac05e847" ]
      }
    }
```

but I haven't thought through it completely. What do you think?

For the other repositories it is straightforward but for the ADC, it's complicated because we have many repositories so we get a proliferation of prefixes which goes to my concerns in #32

**Comment by bcorrie** [comment]
I think there are two complications here:

1. The AKC data model is "complex" in the sense that there are many classes with complex relationships. For example a single `Participant` might be populated in the AKC from several external sources.
2. The ADC is complex because it consists of multiple repositories, so a globally unique ID is not sufficient to find an object, because you have to know the objects repository as well.

So I think I like the idea of having a list of URIs for some (if not all) AKC classes. This means that some (if not all) classes would be a subclass of `ForeignObject `and `ForeignObject` would have a field `source_uris `as an array of URIs as you have above.

As to what goes into the `source_uris` is still a bit unresolved I think, even though #32 is closed. Getting concrete, assume `Particpiant` is a subclass of `ForeignObject` and we have a field `source_uris`, what does this field have in it for a `Participant` whose main metadata is associated with N repertoires in the ADC but whose Genotype comes from VDJBase. So there isn't a single Repertoire that produces the `Particpant` data. And what is the IRI/CURIE that we use to represent the ADC:Repertoire and VDJBASE:Germlineset that contributed to the "creation" of the entity in the AKC?

**Comment by schristley** [comment]
I'm not completely sure of what you are proposing, but I don't feel there is a need to make this overly complicated. We don't require a completely reverse mapping, we just need a simple provenance for the source data. It is probably more constructive to consider the specific cases where we need to do matching between repositories. I think there are just a few cases.

* Match AKC Participant between ADC and VDJbase. This is loosely (ADC.study_id == VDJbase.study_id AND ADC.subject_id = VDJbase.subject_id). I know those ADC fields are in the AKC, just need to verify that those fields are the VDJbase output somewhere.
* Match AKC Chains between ADC, IEDB and IRAD. This will be handled by the hashing solution I'm using.
* Match AKC Investigation between ADC, IEDB and IRAD. This is not possible yet but is preferably done with the AKC archival_id (ADC study_id) though we talked about it in the last schema KG. Randi was going look into the possibility of getting BioProject IDs in the curation process.
* Match AKC References between ADC, IEDB and IRAD. This is a looser form of trying to match the studies, instead we try to match up the publications. This is possible with Pubmed IDs, but some ADC stuff has DOIs instead of Pubmed.
* Match VDJ gene calls between all repositories. This is trickier because OGRDB only has the AIRR curated germline sets but we will resolve this over time with re-annotation.

Though I realize now I'm probably answering a different question then what you posed...

**Comment by schristley** [comment]
> So I think I like the idea of having a list of URIs for some (if not all) AKC classes. This means that some (if not all) classes would be a subclass of `ForeignObject `and `ForeignObject` would have a field `source_uris `as an array of URIs as you have above.

Not subclasses though, just a slot to hold the list of `ForeignObjects`. I also don't think all AKC classes need this slot, only the ones where we want a "LinkOut" to the external source. For example, we aren't going to create links in each AKC `Chain` object to every single `Rearrangement` object that was its "source". That would required a large amount of space to store all of those links without providing much utility.

I think having `source_uris` in AKC `Investigation` that points back to the ADC `Repertoires` seems reasonable, I don't think we need more than that.

**Comment by bcorrie** [comment]
ADC conversion now stores the repertoire_id of those repertoires that contribute to the creation of an AKC object in the slot `source_uris`.

See https://github.com/airr-knowledge/ak-schema/tree/main/examples/adc

**Comment by schristley** [comment]
good for interim milestone
